{{ if .Values.jupyter.enabled -}}

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "dask.fullname" . }}-jupyter
  labels:
    app: {{ template "dask.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "dask.chart" . }}
    component: jupyter
spec:
  replicas: {{ .Values.jupyter.replicas }}
  selector:
    matchLabels:
      app: {{ template "dask.name" . }}
      release: {{ .Release.Name | quote }}
      component: jupyter
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "dask.name" . }}
        release: {{ .Release.Name | quote }}
        component: jupyter
    spec:
      containers:
        - name: {{ template "dask.fullname" . }}-jupyter
          image: "{{ .Values.jupyter.image.repository }}:{{ .Values.jupyter.image.tag }}"
          imagePullPolicy: {{ .Values.jupyter.image.pullPolicy }}
          ports:
            - containerPort: 8888
          resources:
{{ toYaml .Values.jupyter.resources | indent 12 }}
          volumeMounts:
{{ toYaml .Values.jupyter.volumeMounts | indent 12 }}
          env:
            - name: DASK_SCHEDULER_ADDRESS
              value: {{ template "dask.fullname" . }}-scheduler:{{ .Values.scheduler.servicePort }}
{{- if .Values.jupyter.env }}
{{ toYaml .Values.jupyter.env | indent 12 }}
{{- end }}
            - mountPath: /criteo
              name: test-volume
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "dask.fullname" . }}-jupyter-config
        - name: test-volume
          hostPath:
            # directory location on host
            path: /mnt/data
            # this field is optional
            type: Directory
        - name: data
          flexVolume:
            driver: "azure/blobfuse"
            readOnly: false
            secretRef:
              name: blobfusecreds
            options:
              container: "data"
              tmppath: /tmp/datablobfuse
              mountoptions: "--file-cache-timeout-in-seconds=120"
        - name: models
          flexVolume:
            driver: "azure/blobfuse"
            readOnly: false
            secretRef:
              name: blobfusecredsmodel
            options:
              container: "models"
              tmppath: /tmp/modelsblobfuse
              mountoptions: "--file-cache-timeout-in-seconds=120"
        - name: output
          flexVolume:
            driver: "azure/blobfuse"
            readOnly: false
            secretRef:
              name: blobfusecreds
            options:
              container: "output"
              tmppath: /tmp/outputblobfuse
              mountoptions: "--file-cache-timeout-in-seconds=120"

{{ end }}
